using System.Windows.Forms;
using Microsoft.ManagementConsole;

namespace Webcoder.SqlServer.SqlVarMaxConvert
{
    /// <summary>
    /// The root node of the snap-in.
    /// </summary>
    public class RootNode : ScopeNode
    {
        #region Private Fields
        /// <summary>
        /// The "Connect..." dialog.
        /// </summary>
        ConnectServerDialog connectServerDialog = new ConnectServerDialog();
        #endregion

        #region Public Constructors
        /// <summary>
        /// Default constructor for the root node.
        /// </summary>
        public RootNode()
        {
            DisplayName = "SQL VarMax Convert";
            var connect = new SyncAction("Connect...", "Connect to a database server.");
            connect.Triggered += new SyncAction.SyncActionEventHandler(ConnectActionTriggered);
            ActionsPaneItems.Add(connect);
        }
        #endregion

        #region Event Handlers
        /// <summary>
        /// Connect action fired for root node.
        /// </summary>
        /// <param name="sender">The root node this action was generated by.</param>
        /// <param name="e">The action arguments, containing the action object and a sync status object.</param>
        public void ConnectActionTriggered(object sender, SyncActionEventArgs e)
        {
            e.Status.CanCancel = false;
            e.Status.Title = "Connecting...";
            connectServerDialog.ShowDialog();
            if (connectServerDialog.DialogResult != DialogResult.OK) return;
            e.Status.Title = "Connecting to " + connectServerDialog.ServerSelected + "...";
            Children.Add(new ServerNode(connectServerDialog.ServerSelected, e.Status));
        }
        #endregion
    }
}
